# site settings
title: Brafie
subtitle: Brafie Portofolio
email: ariefbuddies@qmail.id
description: A braveries
baseurl: "/"
url: https://forty-jekyll-theme-two.vercel.app # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: 1(707) 999-7976

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
